"""
Simple Facebook Messenger echo bot.

Receives incoming messages from a Facebook Page webhook and sends
the same text back to the sender.
"""

import logging
import os

import requests
from dotenv import load_dotenv
from flask import Flask, request

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

load_dotenv()

app = Flask(__name__)

FB_VERIFY_TOKEN = os.getenv("FB_VERIFY_TOKEN", "")
FB_PAGE_ACCESS_TOKEN = os.getenv("FB_PAGE_ACCESS_TOKEN", "")
print(FB_VERIFY_TOKEN)


def send_fb_message(recipient_id: str, message_text: str) -> bool:
    """Send text message using Facebook Graph API."""
    if not FB_PAGE_ACCESS_TOKEN:
        logger.error("FB_PAGE_ACCESS_TOKEN is missing in environment.")
        return False

    url = f"https://graph.facebook.com/v18.0/me/messages?access_token={FB_PAGE_ACCESS_TOKEN}"
    payload = {
        "recipient": {"id": recipient_id},
        "message": {"text": message_text},
    }

    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code != 200:
            logger.error("Failed to send message: %s", response.text)
            return False
        return True
    except requests.RequestException as exc:
        logger.error("Graph API request failed: %s", exc)
        return False


@app.route("/webhook", methods=["GET"])
def verify_webhook():
    """Meta webhook verification endpoint."""
    mode = request.args.get("hub.mode")
    token = request.args.get("hub.verify_token")
    challenge = request.args.get("hub.challenge")

    if mode == "subscribe" and token == FB_VERIFY_TOKEN:
        logger.info("Webhook verified.")
        return challenge or "", 200

    logger.warning("Webhook verification failed.")
    return "Verification failed", 403


@app.route("/webhook", methods=["POST"])
def webhook():
    """Handle incoming page messages and echo message text."""
    payload = request.get_json(silent=True) or {}

    for entry in payload.get("entry", []):
        for event in entry.get("messaging", []):
            sender_id = event.get("sender", {}).get("id")
            message = event.get("message", {})
            text = message.get("text")

            # Ignore echoes generated by the page itself.
            if message.get("is_echo"):
                continue

            if sender_id and text:
                logger.info("Incoming message from %s: %s", sender_id, text)
                send_fb_message(sender_id, text)

    return "OK", 200


if __name__ == "__main__":
    if not FB_VERIFY_TOKEN or not FB_PAGE_ACCESS_TOKEN:
        logger.warning(
            "Set FB_VERIFY_TOKEN and FB_PAGE_ACCESS_TOKEN in your environment/.env before running."
        )

    app.run(host="0.0.0.0", port=5000, debug=True)
